# Generated by Django 4.1 on 2023-04-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApplicationTwo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
    ]
